name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with autopep8
      run: |
        pip install autopep8
        autopep8 --exit-code interpreter.py
    - name: Test with unittest
      run: |
        python -m unittest interpreter
